<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FYP CLO Assessment Report</title>
    <style>
        @page {
            margin: 20mm 15mm 20mm 15mm;
            size: A4 landscape;
        }
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10px;
            color: #333;
            margin: 0;
            padding: 10px;
        }
        .header {
            text-align: center;
            margin-bottom: 15px;
            padding-bottom: 10px;
            border-bottom: 2px solid #003A6C;
        }
        .header h1 {
            font-size: 18px;
            color: #003A6C;
            margin-bottom: 5px;
        }
        .header p {
            font-size: 10px;
            color: #666;
        }
        .meta-info {
            margin-bottom: 12px;
            font-size: 9px;
            color: #666;
            line-height: 1.4;
        }
        .table-container {
            width: 100%;
            overflow: visible;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
            table-layout: auto;
        }
        thead {
            background-color: #003A6C;
            color: white;
        }
        th {
            padding: 7px 5px;
            text-align: center;
            font-weight: bold;
            font-size: 8px;
            border: 1px solid #002a4f;
            line-height: 1.2;
        }
        td {
            padding: 5px;
            border: 1px solid #ddd;
            font-size: 8px;
            line-height: 1.3;
        }
        tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .text-center {
            text-align: center;
        }
        .text-left {
            text-align: left;
        }
        .status-badge {
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 8px;
            font-weight: bold;
            display: inline-block;
        }
        .status-not-started {
            background-color: #e5e7eb;
            color: #374151;
        }
        .status-in-progress {
            background-color: #fef3c7;
            color: #92400e;
        }
        .status-completed {
            background-color: #d1fae5;
            color: #065f46;
        }
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 8px;
            color: #666;
            padding: 8px 0;
            border-top: 1px solid #ddd;
            margin: 0 12mm;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>FYP CLO Assessment Report</h1>
        <p>Final Year Project - Course Learning Outcomes Breakdown</p>
    </div>

    <div class="meta-info">
        <p><strong>Generated by:</strong> {{ $generatedBy }} | <strong>Generated on:</strong> {{ $generatedAt->format('F d, Y \a\t H:i:s') }}</p>
        <p><strong>Total Students:</strong> {{ $students->count() }} | <strong>CLOs:</strong> {{ implode(', ', $cloCodes) }}</p>
    </div>

    <div class="table-container">
    <table>
        <thead>
            <tr>
                <th style="width: 3%;">#</th>
                <th style="width: 15%;" class="text-left">Student Name</th>
                <th style="width: 10%;">Matric No</th>
                <th style="width: 8%;">Group</th>
                <th style="width: 12%;">Company</th>
                @foreach($cloCodes as $clo)
                <th style="width: {{ 40 / count($cloCodes) }}%;">{{ $clo }}</th>
                @endforeach
                <th style="width: 8%;">Total</th>
                <th style="width: 8%;">Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($students as $index => $student)
            <tr>
                <td class="text-center">{{ $index + 1 }}</td>
                <td class="text-left">{{ $student->name ?? 'N/A' }}</td>
                <td class="text-center">{{ $student->matric_no ?? 'N/A' }}</td>
                <td class="text-center">{{ $student->group->name ?? 'N/A' }}</td>
                <td class="text-center">{{ $student->company->company_name ?? 'N/A' }}</td>
                @php $totalScore = 0; @endphp
                @foreach($cloCodes as $clo)
                    @php
                        $score = $student->clo_scores[$clo] ?? 0;
                        $totalScore += $score;
                    @endphp
                    <td class="text-center">{{ number_format($score, 2) }}</td>
                @endforeach
                <td class="text-center"><strong>{{ number_format($totalScore, 2) }}</strong></td>
                <td class="text-center">
                    @if(($student->overall_status_label ?? 'Not Started') === 'Completed')
                        <span class="status-badge status-completed">Completed</span>
                    @elseif(($student->overall_status_label ?? 'Not Started') === 'In Progress')
                        <span class="status-badge status-in-progress">In Progress</span>
                    @else
                        <span class="status-badge status-not-started">Not Started</span>
                    @endif
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="{{ 6 + count($cloCodes) }}" class="text-center" style="padding: 20px;">No student data available</td>
            </tr>
            @endforelse
        </tbody>
    </table>
    </div>

    <div class="footer">
        <p>Generated by WBL Management System | {{ $generatedAt->format('Y-m-d H:i:s') }}</p>
    </div>

    <script type="text/php">
        if (isset($pdf)) {
            $text = "Page {PAGE_NUM} of {PAGE_COUNT}";
            $size = 8;
            $font = $fontMetrics->getFont("DejaVu Sans");
            $width = $fontMetrics->get_text_width($text, $font, $size) / 2;
            $x = ($pdf->get_width() - $width) / 2;
            $y = $pdf->get_height() - 25;
            $pdf->page_text($x, $y, $text, $font, $size);
        }
    </script>
</body>
</html>
