<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WBL Student Performance Report – LI</title>
    <style>
        @page {
            margin: 20mm 15mm 20mm 15mm;
            size: A4 landscape;
        }
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10px;
            color: #333;
            margin: 0;
            padding: 10px;
        }
        .header {
            text-align: center;
            margin-bottom: 15px;
            padding-bottom: 10px;
            border-bottom: 2px solid #003A6C;
        }
        .header h1 {
            font-size: 18px;
            color: #003A6C;
            margin-bottom: 5px;
        }
        .header p {
            font-size: 10px;
            color: #666;
        }
        .meta-info {
            margin-bottom: 12px;
            font-size: 9px;
            color: #666;
            line-height: 1.4;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }
        thead {
            background-color: #003A6C;
            color: white;
        }
        th {
            padding: 7px 5px;
            text-align: left;
            font-weight: bold;
            font-size: 8px;
            border: 1px solid #002a4f;
        }
        td {
            padding: 5px;
            border: 1px solid #ddd;
            font-size: 8px;
        }
        tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .text-center { text-align: center; }
        .status-badge {
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 7px;
            font-weight: bold;
            text-transform: uppercase;
        }
        .status-not-started { background-color: #f3f4f6; color: #6b7280; }
        .status-in-progress { background-color: #fef3c7; color: #d97706; }
        .status-completed { background-color: #d1fae5; color: #059669; }
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 8px;
            color: #666;
            padding: 8px 0;
            border-top: 1px solid #ddd;
            margin: 0 15mm;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>WBL Student Performance Report – LI</h1>
        <p>Industrial Training</p>
    </div>

    <div class="meta-info">
        <p><strong>Generated by:</strong> {{ $adminName }} | <strong>Generated on:</strong> {{ $generatedAt->format('F d, Y \a\t H:i:s') }}</p>
        <p><strong>Total Students:</strong> {{ $students->count() }} | <strong>Weights:</strong> Supervisor ({{ number_format($supervisorWeight, 1) }}%), Industry Coach ({{ number_format($icWeight, 1) }}%)</p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 3%;">#</th>
                <th style="width: 20%;">Student Name</th>
                <th style="width: 12%;">Matric No</th>
                <th style="width: 10%;">Group</th>
                <th style="width: 12%;" class="text-center">Supervisor ({{ number_format($supervisorWeight, 1) }}%)</th>
                <th style="width: 12%;" class="text-center">IC ({{ number_format($icWeight, 1) }}%)</th>
                <th style="width: 12%;" class="text-center">Final Score ({{ number_format($totalWeight, 1) }}%)</th>
                <th style="width: 10%;" class="text-center">Status</th>
                <th style="width: 7%;" class="text-center">Progress</th>
            </tr>
        </thead>
        <tbody>
            @foreach($students as $index => $student)
            <tr>
                <td class="text-center">{{ $index + 1 }}</td>
                <td>{{ $student->name }}</td>
                <td>{{ $student->matric_no }}</td>
                <td>{{ $student->group->name ?? 'N/A' }}</td>
                <td class="text-center">{{ number_format($student->supervisor_score, 2) }}%</td>
                <td class="text-center">{{ number_format($student->ic_score, 2) }}%</td>
                <td class="text-center"><strong>{{ number_format($student->final_score, 2) }}%</strong></td>
                <td class="text-center">
                    @if($student->status == 'completed')
                        <span class="status-badge status-completed">Completed</span>
                    @elseif($student->status == 'in_progress')
                        <span class="status-badge status-in-progress">In Progress</span>
                    @else
                        <span class="status-badge status-not-started">Not Started</span>
                    @endif
                </td>
                <td class="text-center">{{ number_format($student->progress, 0) }}%</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by WBL Management System | {{ $generatedAt->format('Y-m-d H:i:s') }}
    </div>
</body>
</html>
